sonar.projectKey=ramisaferdous_Password-Generator
sonar.organization=ramisaferdous


# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=Password-Generator
sonar.projectVersion=1.0
sonar.sources=Password Generator/src
sonar.exclusions=**/GeneratorTest.java
sonar.java.binaries=Password Generator/bin
sonar.sourceEncoding=UTF-8
